# Generated by Django 2.1.2 on 2018-10-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
